[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
monitor_speed = 115200

lib_deps =
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
